# Bootstrap
source ~/.shell/bootstrap.sh

# Stops config if this terminal is non-interactive
[[ -z "$PS1" ]] && return



# External settings
source ~/.shell/external.sh

# Aliases
source ~/.shell/aliases.sh

# Custom prompt
#source ~/.zsh/prompt.zsh

# External plugins (initialized after)
#source ~/.zsh/plugins_after.zsh

# Allow local customizations in the ~/.shell_local_after file
if [ -f ~/.shell_local_after ]; then
    source ~/.shell_local_after
fi

# Allow local customizations in the ~/.zshrc_local_after file
if [ -f ~/.zshrc_local_after ]; then
    source ~/.zshrc_local_after
fi

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Report CPU usage for commands running longer than 45 seconds
REPORTTIME=45

# FILE SOURCING BLOCK

# Check for antigen and install if not
if [ ! -f "$HOME/antigen.zsh" ] 
then
    echo "Antigen not installed. Pulling." 
    curl -L git.io/antigen > $HOME/antigen.zsh
fi

# Source antigenrc
[[ -f ~/.antigenrc ]] && . ~/.antigenrc

# fzf completions
[[ -f ~/.fzf.zsh ]] && . ~/.fzf.zsh

# Configure zsh prompt. Listed last to override antigen theme settings
#PROMPT="> "
RPROMT=" "